/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RFIDManagement.view;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/**
 *
 * @author ypg5097
 */
public class SearchCard extends javax.swing.JFrame {

    private String cname;
    private String surl;
    private String turl;
    private File file;
    private String oldName;
    private String oldsUrl;
    private String oldtUrl;

    /**
     * Creates new form CardSearchResult
     */
    public SearchCard(ArrayList<String> toPass, File file) {
        if (toPass != null && file != null) {
            initComponents();
            this.cNameTxt.setText(toPass.get(0));
            this.sUrlTxt.setText(toPass.get(2));
            this.tUrlTxt.setText(toPass.get(1));
            this.file = file;
        } else {
            initComponents();
        }
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("5.png")));
    }

    private void updateAttributs(String name, String surl, String turl) {
        this.cname = name;
        this.surl = surl;
        this.turl = turl;
    }

    private void resetAttributs() {
        this.cNameTxt.setText("");
        this.sUrlTxt.setText("");
        this.tUrlTxt.setText("");
    }

    public boolean checkName(String toCheck) {
        if (toCheck.isEmpty()) {
            return false;
        }
        return true;
    }

    public boolean checkURL(String toCheck) {
        if (toCheck.isEmpty()) {
            return false;
        }
        int k = 0;
        toCheck = toCheck.toUpperCase();
        char[] stringToCharArray = toCheck.toCharArray();
        if (stringToCharArray.length < 10) {
            return false;
        }
        char[] http = new char[]{'H', 'T', 'T', 'P'};
        for (int i = 0; i < 4; i++) {
            if (stringToCharArray[i] == http[i]) {
                k++;
            }
        }
        if (k == 4) {
            return true;
        }
        return false;
    }

    private void enableEdit(Boolean b) {
        deleteButton.setVisible(b);
        saveButton.setVisible(b);
        cNameTxt.setEnabled(b);
        sUrlTxt.setEnabled(b);
        tUrlTxt.setEnabled(b);
        if (b) {
            editButton.setText("Cancel");
        } else {
            editButton.setText("Edit");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultLable = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        cNameLab = new javax.swing.JLabel();
        cNameTxt = new javax.swing.JTextField();
        sUrlLab = new javax.swing.JLabel();
        sUrlTxt = new javax.swing.JTextField();
        tUrlLab = new javax.swing.JLabel();
        tUrlTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultLable.setText("Search Result:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cNameLab.setText("Card Name:");

        cNameTxt.setEnabled(false);

        sUrlLab.setText("Studnet Url:");

        sUrlTxt.setEnabled(false);

        tUrlLab.setText("Teacher Url:");

        tUrlTxt.setEnabled(false);

        saveButton.setVisible(false);
        deleteButton.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 167, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(editButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tUrlLab)
                            .addComponent(sUrlLab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sUrlTxt)
                            .addComponent(tUrlTxt, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultLable)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cNameLab)
                        .addGap(12, 12, 12)
                        .addComponent(cNameTxt)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNameLab)
                    .addComponent(cNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sUrlLab)
                    .addComponent(sUrlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tUrlLab)
                    .addComponent(tUrlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(deleteButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if (editButton.getText() == "Edit") {
            oldName = cNameTxt.getText();
            oldsUrl = sUrlTxt.getText();
            oldtUrl = tUrlTxt.getText();
            enableEdit(true);
        } else {
            cNameTxt.setText(oldName);
            sUrlTxt.setText(oldsUrl);
            tUrlTxt.setText(oldtUrl);
            enableEdit(false);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (checkName(cNameTxt.getText())) {
            if (checkURL(sUrlTxt.getText())) {
                if (checkURL(tUrlTxt.getText())) {
                    this.updateAttributs(cNameTxt.getText(), sUrlTxt.getText(), tUrlTxt.getText());
                    DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
                    DocumentBuilder dBuilder = null;
                    Document doc = null;
                    try {
                        dBuilder = dbFactory.newDocumentBuilder();
                        doc = dBuilder.parse(file);
                        doc.getElementsByTagName("name").item(0).setTextContent(cname);
                        doc.getElementsByTagName("stuUrl").item(0).setTextContent(surl);
                        doc.getElementsByTagName("teachUrl").item(0).setTextContent(turl);
                        TransformerFactory transformerFactory = TransformerFactory.newInstance();
                        Transformer transformer = transformerFactory.newTransformer();
                        DOMSource source = new DOMSource(doc);
                        StreamResult result = new StreamResult(file);
                        transformer.transform(source, result);
                        enableEdit(false);
                        JOptionPane.showMessageDialog(null, "Edit completed!");
                    } catch (IOException | SAXException | ParserConfigurationException | TransformerException ex) {
                        Logger.getLogger(SearchStudent.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Invalid teacher URL input(too short or not start with 'http://')!",
                            "Warning",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(null,
                        "Invalid student URL input(too short or not start with 'http://')!",
                        "Warning",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Name can not be empty!",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the record?", "Warning", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.file.delete();
            this.resetAttributs();
            this.dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchCard(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cNameLab;
    private javax.swing.JTextField cNameTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel resultLable;
    private javax.swing.JLabel sUrlLab;
    private javax.swing.JTextField sUrlTxt;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel tUrlLab;
    private javax.swing.JTextField tUrlTxt;
    // End of variables declaration//GEN-END:variables
}
